apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: rsvpapp
  labels:
    name: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: rsvpapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: "mongodb"
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6
          ports:
            - containerPort: 27017
